### PR TITLE
Change wording & connect to mongdb before listen

### PR DESCRIPTION
**Pull request by environmentfile**
Hi! I have changed the wording on uploading errors & the email verify thingy I have also made it so that it will connect to the MongoDB cluster before listening. In my mind, this makes more sense.

### CODE REVIEW

**Comment by vanility0001** [comment]
closed

**Comment by environmentfile** [comment]
Im going to close you if you aren't careful.

**Comment by vanility0001** [comment]
close it then pussio
avatar_829614

**Comment by aspectiscool** [comment]
everything looks good except commit [01b104f](https://github.com/astral-re/Server/pull/4/commits/01b104f505873378a7a3db95e9e72bdf5b91ca6f), the wording is meant to not be punctual, change that and I'll merge.

**Comment by vanility0001** [comment]
Horrible features, closed.

**Pull request closed without merging**
